#!/usr/bin/env python3
"""Generate the landing and console token files from design/tokens.css.

    python3 design/sync-tokens.py           # write both targets (and mirror fonts)
    python3 design/sync-tokens.py --check   # exit 1 if either target is stale

Why generate instead of sharing one file: the landing is a build-free static
nginx image whose docker context is ``landing/``, and the console is a
Vite/Tailwind app whose context is ``console/``. Neither context can reach a
file above it, so a single shared file is not physically possible without
widening both build contexts. Generating from one source is the same trade
k3s-platform/gen-grafana-dashboards.py already makes.

Why the console gets literal values rather than ``var(--vx-*)`` indirection:
Tailwind v4 needs to *parse* a colour to build an opacity modifier, so
``bg-accent/12`` only works when ``--color-accent`` holds a real colour. Passing
a ``var()`` through would silently produce no rule.

``--check`` cannot run *inside* either image build, for the same reason a shared
file is impossible: neither docker context can reach ``design/``. It runs in
``build-images.sh``, which is the one place that can see all three paths, and a
stale target fails the build there before anything is built.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = HERE / "tokens.css"

LANDING_CSS = ROOT / "landing" / "assets" / "tokens.v2.css"
CONSOLE_CSS = ROOT / "console" / "src" / "tokens.generated.css"

LANDING_FONTS = ROOT / "landing" / "assets" / "fonts"
CONSOLE_FONTS = ROOT / "console" / "public" / "fonts"

BANNER = (
    "/* GENERATED by design/sync-tokens.py from design/tokens.css — DO NOT EDIT.\n"
    "   Edit design/tokens.css and re-run the script. */\n"
)

# --vx-<name> -> the Tailwind v4 theme namespace it must land in for the right
# utilities to be generated. Anything not matched here is emitted as a plain
# custom property, which is correct for values Tailwind has no namespace for.
NAMESPACES: tuple[tuple[str, str], ...] = (
    ("font-", "--font-"),        # --vx-font-sans     -> font-sans
    ("text-", "--text-"),        # --vx-text-lg       -> text-lg
    ("tracking-", "--tracking-"),
    ("ease-", "--ease-"),
)

# Explicit renames where a mechanical rule would collide with a Tailwind default
# or produce an empty name (--vx-radius would become "--radius-").
RENAMES: dict[str, str] = {
    "radius": "--radius-card",
    "radius-sm": "--radius-chip",
    "radius-lg": "--radius-panel",
    "radius-pill": "--radius-pill",
    "shadow": "--shadow-panel",
    "shadow-accent": "--shadow-accent",
    "ease": "--ease-soft",
}

# Values Tailwind has no namespace for: emitted into a plain :root block.
#
# The gradients are here for a hard reason, not a stylistic one: Tailwind's colour
# namespace generates `bg-*` as `background-color`, and `background-color:
# linear-gradient(...)` is invalid, so a gradient in @theme silently produces
# nothing. Consumers hand-write .bg-grad-brand / .text-grad against these, which
# is also what dicomsegvr/dashboard/src/index.css:55 does.
PLAIN = {"maxw", "maxw-prose", "draw-ms", "hairline", "grad-brand", "grad-mesh"}

# Comments are stripped before parsing, so a declaration may carry a trailing
# `/* why */` and a value may span lines. The previous pattern was anchored to
# both ends of a single line, which meant EIGHT of 56 tokens — including
# accent-hi, accent-ink and shadow-accent — were silently invisible to this
# script while --check still reported "in sync", because it compared generated
# output to disk rather than checking coverage of the source. See COVERAGE below.
_COMMENT = re.compile(r"/\*.*?\*/", re.S)
_DECL = re.compile(r"--vx-([a-z0-9-]+)\s*:\s*([^;]+);", re.S)
# Deliberately looser than _DECL: any token-looking declaration at all. If the two
# disagree, the parser is dropping something and the build must fail.
_COVERAGE = re.compile(r"--vx-[a-z0-9-]+\s*:")

FONT_FACES = """
/* Self-hosted latin subsets — the same two faces DicomSegVR ships, reused from
   its landing verbatim. Two files, 59 KB total: Sans is a variable font covering
   300-800 in one file. No CDN, because a hospital workstation may have no
   outbound internet — the same reason oidc-client-ts is bundled. */
@font-face {{
  font-family: "Geist";
  font-style: normal;
  font-weight: 300 800;
  font-display: swap;
  src: url("{p}/Geist-latin.woff2") format("woff2");
}}
@font-face {{
  font-family: "Geist Mono";
  font-style: normal;
  font-weight: 400 600;
  font-display: swap;
  src: url("{p}/GeistMono-latin.woff2") format("woff2");
}}
"""


def parse(text: str) -> list[tuple[str, str]]:
    """Declarations from the source, comments removed, values whitespace-collapsed."""
    stripped = _COMMENT.sub("", text)
    decls = [(name, " ".join(value.split())) for name, value in _DECL.findall(stripped)]
    if not decls:
        raise SystemExit(f"no --vx-* declarations found in {SOURCE}")

    # The guard that the old --check could not provide: every token the loose scan
    # can see must have been parsed. Without this, a pattern change that stops
    # matching some declaration shape loses tokens with no failing output.
    found = len(_COVERAGE.findall(stripped))
    if found != len(decls):
        raise SystemExit(
            f"parser coverage mismatch in {SOURCE}: "
            f"{found} declaration(s) present, {len(decls)} parsed"
        )

    seen: set[str] = set()
    for name, _ in decls:
        if name in seen:
            raise SystemExit(f"duplicate token --vx-{name} in {SOURCE}")
        seen.add(name)
    return decls


def theme_name(name: str) -> str | None:
    """The Tailwind @theme variable for a token, or None if it stays plain."""
    if name in PLAIN:
        return None
    # STRUCTURE COLOURS STAY OUT OF @theme.
    #
    # Tailwind v4 prunes any @theme colour variable that no utility class references,
    # and these are never used as utilities — they are chosen at RUNTIME from a
    # prompt's text and read as `var(...)` in an inline style, which the scanner
    # cannot see. Measured: of 23 `--color-s-*` variables, exactly ONE reached the
    # built CSS, and only because a comment in lib/structures.ts happened to contain
    # the string "text-s-liver" and the scanner took it for a class candidate. Every
    # other structure contour and prompt chip rendered `stroke: none`.
    #
    # Emitting them as --vx-s-* also means the console and the landing page now name
    # the same colour identically (hero.v2.js already builds `var(--vx-<token>)`),
    # which is the point of the ledger being one shared device.
    if name.startswith("s-"):
        return None
    if name in RENAMES:
        return RENAMES[name]
    for prefix, replacement in NAMESPACES:
        if name.startswith(prefix):
            return replacement + name[len(prefix):]
    # Everything else is a colour: --vx-surface-2 -> --color-surface-2,
    # --vx-s-liver -> --color-s-liver.
    return "--color-" + name


def render_landing(decls: list[tuple[str, str]]) -> str:
    """The landing links this directly, so it keeps the --vx-* names as written.

    Rebuilt from the parsed declarations rather than echoing the source file:
    tokens.css carries ~4 KB of internal design rationale — why the old amber was
    wrong, which DicomSegVR files have drifted — and none of that belongs in a
    public asset served to customers. The banner points at the source instead.
    """
    body = "\n".join(f"  --vx-{name}: {value};" for name, value in decls)
    return (
        BANNER
        + FONT_FACES.format(p="/assets/fonts")
        + "\n:root {\n"
        + body
        + "\n}\n"
    )


def render_console(decls: list[tuple[str, str]]) -> str:
    theme: list[str] = []
    plain: list[str] = []
    for name, value in decls:
        target = theme_name(name)
        if target is None:
            plain.append(f"  --vx-{name}: {value};")
        else:
            theme.append(f"  {target}: {value};")

    # No `@import "tailwindcss"` here — console/src/index.css owns that, so both
    # imports sit at the top of one file and the flattened order stays obvious.
    out = [
        BANNER,
        FONT_FACES.format(p="/dashboard/fonts"),
        "\n/* Tailwind v4 generates utilities from these: bg-surface, text-accent,",
        "   border-border, rounded-card, font-mono, text-lg, shadow-accent, and the",
        "   opacity modifiers (bg-accent/12) which need literal colours to work. */",
        "@theme {",
        *theme,
        "}\n",
        "/* Values Tailwind has no namespace for; referenced directly as var(). */",
        ":root {",
        *plain,
        "}",
        "",
    ]
    return "\n".join(out)


def mirror_fonts(check: bool) -> list[str]:
    stale: list[str] = []
    if not LANDING_FONTS.is_dir():
        raise SystemExit(f"missing font source directory {LANDING_FONTS}")
    fonts = sorted(LANDING_FONTS.glob("*.woff2"))
    if not fonts:
        raise SystemExit(f"no .woff2 files in {LANDING_FONTS}")
    CONSOLE_FONTS.mkdir(parents=True, exist_ok=True)
    for src in fonts:
        dst = CONSOLE_FONTS / src.name
        same = dst.exists() and dst.read_bytes() == src.read_bytes()
        if same:
            continue
        stale.append(str(dst.relative_to(ROOT)))
        if not check:
            shutil.copy2(src, dst)
    return stale


def main() -> int:
    check = "--check" in sys.argv[1:]
    source_text = SOURCE.read_text()
    decls = parse(source_text)

    targets = {LANDING_CSS: render_landing(decls), CONSOLE_CSS: render_console(decls)}

    stale: list[str] = []
    for path, content in targets.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    stale += mirror_fonts(check)

    if check:
        if stale:
            print("STALE — run design/sync-tokens.py:", file=sys.stderr)
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            return 1
        print(f"tokens in sync ({len(decls)} tokens)")
        return 0

    if stale:
        print(f"wrote {len(stale)} file(s) from {len(decls)} tokens:")
        for s in stale:
            print(f"  {s}")
    else:
        print(f"already in sync ({len(decls)} tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
